# Generated by Django 5.0.4 on 2024-04-21 00:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.UUIDField(auto_created=True, default=uuid.UUID('7f4fdadc-88cb-4a47-8954-ba97b734d671'), primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=300)),
                ('user_national_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_available_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user_locked_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_backend.userinfo')),
            ],
        ),
    ]
