# Generated by Django 5.0.4 on 2024-04-21 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_id',
            new_name='user_info',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('4589ccff-34e1-457a-9ea6-3b022308b97c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
