# Generated by Django 5.0.4 on 2024-04-21 00:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_backend', '0003_alter_userinfo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_info',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('17795824-6f7d-44c8-b23e-19dfc2ec627c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
