# Generated by Django 5.0.4 on 2024-04-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_backend', '0004_remove_useraccount_user_info_alter_userinfo_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
