# Generated by Django 5.0.4 on 2024-04-21 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_backend', '0005_delete_useraccount_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.UUIDField(auto_created=True, default=uuid.UUID('c388e177-d53b-4690-9f64-874bbd34d695'), primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=300)),
                ('user_national_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_available_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user_locked_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_backend.userinfo')),
            ],
        ),
    ]
