# Generated by Django 5.0.4 on 2024-04-21 01:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_backend', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('5285bcb4-8692-41a2-896a-d4620348529a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
