# Generated by Django 5.0.4 on 2024-04-23 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_backend', '0007_alter_userinfo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_available_amount',
            new_name='available_amount',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_locked_amount',
            new_name='locked_amount',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_national_id',
            new_name='national_id',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_name',
            new_name='user_info',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_info',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_backend.useraccount'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
