# Generated by Django 5.0.4 on 2024-04-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_backend', '0008_rename_user_available_amount_useraccount_available_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_account',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
