# Generated by Django 5.0.4 on 2024-04-24 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_backend', '0009_remove_userinfo_user_account_delete_useraccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformations',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_info', models.CharField(max_length=300)),
                ('national_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('locked_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_backend.userinformations')),
            ],
        ),
    ]
