# Generated by Django 5.0.4 on 2024-04-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_backend', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(default='Spot', max_length=50),
        ),
    ]
